export const emotionColors = {
  joy:            '#4ade80',
  excitement:     '#f472b6',
  admiration:     '#34d399',
  gratitude:      '#34d399',
  pride:          '#a3e635',
  relief:         '#67e8f9',
  curiosity:      '#60a5fa',
  sadness:        '#f87171',
  grief:          '#f43f5e',
  anger:          '#fbbf24',
  annoyance:      '#fcd34d',
  disapproval:    '#fb923c',
  disappointment: '#fca5a5',
  fear:           '#a78bfa',
  anxiety:        '#c084fc',
  embarrassment:  '#f9a8d4',
  stress:         '#fb923c',
  surprise:       '#60a5fa',
  loneliness:     '#94a3b8',
  mixed:          '#818cf8',
  neutral:        '#9ca3af',
  disgust:        '#a3a3a3',
}

export const emotionLabels = {
  joy:            'Joyful',
  excitement:     'Excited',
  admiration:     'Admiring',
  gratitude:      'Grateful',
  pride:          'Proud',
  relief:         'Relieved',
  curiosity:      'Curious',
  sadness:        'Sad',
  grief:          'Grieving',
  anger:          'Angry',
  annoyance:      'Annoyed',
  disapproval:    'Disapproving',
  disappointment: 'Disappointed',
  fear:           'Fearful',
  anxiety:        'Anxious',
  embarrassment:  'Embarrassed',
  stress:         'Stressed',
  surprise:       'Surprised',
  loneliness:     'Lonely',
  mixed:          'Mixed feelings',
  neutral:        'Neutral',
  disgust:        'Disgusted',
}

export const accentColors = [
  { key: 'blue', label: 'Blue', hue: 220, hex: '#3b82f6' },
  { key: 'rose', label: 'Rose', hue: 340, hex: '#f43f5e' },
  { key: 'emerald', label: 'Emerald', hue: 150, hex: '#10b981' },
  { key: 'amber', label: 'Amber', hue: 38, hex: '#f59e0b' },
  { key: 'violet', label: 'Violet', hue: 260, hex: '#8b5cf6' },
  { key: 'teal', label: 'Teal', hue: 170, hex: '#14b8a6' },
  { key: 'orange', label: 'Orange', hue: 24, hex: '#f97316' },
  { key: 'pink', label: 'Pink', hue: 320, hex: '#ec4899' },
]
